---
- hosts: all
- name: update ansible configs...
  import_playbook: '/src/ansible-playbooks/files/playbooks/update-git.yml'
- name: update opensuse nodes...
  import_playbook: '/src/ansible-playbooks/files/playbooks/update-opensuse-mgmt.yml'