---
- hosts: opensusemgmt
  tasks:
    - name: update opensuse mgmt vms...
      zypper:
        name: '*'
        state: dist-upgrade
        extra_args: '--no-allow-vendor-change --allow-arch-change'
    - name: verify packages are installed...
      zypper:
        name: python-xml
        state: present
    - name: reboot opensuse mgmt vms...
      reboot: