---
- hosts: opensuse-mgmt
  tasks:
    - name: run zypper refresh...
      zypper: 
        update_cache: yes
    - name: run zypper update...
      zypper:
        name: '*'
        state: dist-upgrade
        extra_args: '--no-allow-vendor-change --allow-arch-change'