---
- hosts: opensusemgmt
  tasks:
    - name: run zypper update...
      zypper:
        name: '*'
        state: latest
    - name: verify packages are installed...
      zypper:
        name: python-xml
        state: present